# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/manuelmai',
                'doc_host': 'https://maimanuel.github.io',
                'git_url': 'https://github.com/maimanuel/manuelmai',
                'lib_path': 'manuelmai'},
  'syms': {'manuelmai.core': {'manuelmai.core.foo': ('core.html#foo', 'manuelmai/core.py')}}}